name: share_chairs
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3

  firebase_auth: ^3.0.1
  
  firebase_core: ^1.4.0
  
  firebase_storage: ^10.0.1
  
  firebase_analytics: ^8.2.0
  
  firebase_database: ^7.1.2
  
  cloud_firestore: ^2.4.0

  date_format: ^2.0.3

  form_field_validator: ^1.1.0

  image_picker: ^0.8.3+1

  image_cropper: ^1.4.0

  intl: ^0.17.0

  badges: ^2.0.1

  flutter_switch: ^0.3.2

  flutter_bloc: ^7.3.0

  equatable: ^2.0.3

  cupertino_icons: ^1.0.2

  shared_preferences: ^2.0.7

  cached_network_image: ^3.1.0
  
  api_cache_manager: ^1.0.2

  page_indicator: ^0.4.1

  awesome_notifications: ^0.0.6+11

  lottie: ^1.1.0

  timeago: ^3.1.0

  pull_to_refresh: ^2.0.0

  fluttertoast: ^8.0.8

  permission_handler: ^8.1.6

  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/launch_logo.png"


flutter:

  uses-material-design: true

  assets:
  - assets/lottie/
  - assets/images/
  - assets/icons/
